#!/bin/bash
reminder(){
while true
do
   zenity --text-info \
    --title="REMINDER" \
    --width=500 \
    --height=400 \
    --ok-label="ADD NEW EVENT" \
    --cancel-label="Go Back" \
   --filename="$1.txt"   # Displays text information dialog 
   
   if [ $? -eq 1 ] #check if cancel label has been selected
   then
       break #if true exits the loop
   else
       ADD_EVENT=$(zenity --entry --title="ADD an event"--text="Add an event on $Date" --title="NEW EVENT" --width=500 --height=300) #displays a text entry dialog  and user input is saved in variable ADD_EVENT
       echo "$ADD_EVENT">>"$1.txt" #user input is appended in a file
   fi
done   
}


Calendar(){
while true
do
    Date=$(zenity --calendar --text="select a date to add an event" --ok-label "Add event" --cancel-label "cancel" --width=600 --height=400 --title="SELECT A DATE" --date-format='%d.%m.%Y' ) # Displays the calendar dialog box and store the date chosen in variable $Date
   
   if [ $? -eq 1 ] #$? = was last command succesfull . Answer is 0 means 'yes ok-label has been selected'. Non-zero values means 'No cancel-label has been selected'
   then 
      break
   fi       
   FILENAME="$Date.txt" #The file is assigned to variable FILENAME
   if [ -f "$FILENAME" ] # check if the file with thay specific date exists
   then
       reminder "$Date" #if true reminder of that specific date is called and performs what is in the function reminder 
   else
       ADD_EVENT=$(zenity --entry --title="ADD AN EVENT" --text="Add an event on $Date" --width=500 --height=300) # if false it displays an entry box and    the user input is stored in variable ADD_EVENT
       echo "$ADD_EVENT">>"$FILENAME" #The user input is stored in the file FILENAME="Date.txt" which is a specific date
       reminder "$Date"
   fi
done
}
Calendar
